convert-elements: convert-elements.cpp
	g++ -oconvert-elements -DCONVERTELEMENTS -O3 -Wall convert-elements.cpp

convert-elements.exe: convert-elements.cpp
	g++ -oconvert-elements.exe -DCONVERTELEMENTS -DWIN -O3 -Wall convert-elements.cpp -static-libgcc -static-libstdc++
